language: c++

dist: xenial

services:
  - docker

branches:
  only:
    - master
    - test-fixes

# Pull the latest images
before_install:
  - "docker pull faasm/testing"
  - "docker pull faasm/upload"
  - "docker pull faasm/redis"

script:
  - "docker-compose -f docker-compose-test.yml run tester /usr/local/code/faasm/bin/ci_run.sh"

notifications:
  email:
    on_success: never
    on_failure: always
