language: c++

dist: xenial

# We want to clone only the submodules we need for the build
git:
  submodules: false

services:
  - docker

branches:
  only:
    - master
    - matrices-2

before_install:
  - "./bin/ci_pull.sh"

script:
  - "docker-compose -f docker-compose-test.yml run tester /usr/local/code/faasm/bin/ci_run.sh"

notifications:
  email:
    on_success: never
    on_failure: always
