version: "3"

services:
  redis:
    image: faasm/redis:${FAASM_VERSION}

  minio:
    image: minio/minio
    command: server /data/minio
    ports:
      - "9000:9000"
    volumes:
      - ./dev/minio/data:/data/minio

  faabric-cli:
    image: ${FAABRIC_CLI_IMAGE}
    working_dir: /code/faabric
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - redis
      - minio
    environment:
      - FUNCTION_STORAGE=local
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    volumes:
      - ./faabric:/code/faabric
      - ./dev/faabric/build:/build/faabric
      - ./dev/faasm-local:/usr/local/faasm
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  faasm-cli:
    image: ${FAASM_CLI_IMAGE}
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - redis
      - minio
    environment:
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=redis
      - REDIS_STATE_HOST=redis
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build:/build/faasm/
      - ./dev/faasm-local:/usr/local/faasm
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  cpp-cli:
    image: ${CPP_CLI_IMAGE}
    working_dir: /code/cpp
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - redis
      - minio
    environment:
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    volumes:
      - ./clients/cpp:/code/cpp
      - ./dev/cpp/build:/build/cpp
      - ./dev/faasm-local:/usr/local/faasm
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  python-cli:
    image: ${PYTHON_CLI_IMAGE}
    working_dir: /code/python
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - redis
      - minio
    environment:
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    volumes:
      - ./clients/python:/code/python
      - ./dev/faasm-local:/usr/local/faasm
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  vector:
    image: netflixoss/vector:latest
    depends_on:
      - faasm-cli
    network_mode: host
    ports:
      - "80:80"
