version: "3"

# -------------------------------
# Development set-up for the CLI
# -------------------------------

services:
  redis:
    image: faasm/redis:${FAASM_VERSION}

  cli:
    image: ${CLI_IMAGE}
    volumes:
        - .:/usr/local/code/faasm
        - ./build:/build/faasm
        - ./container/machine-code:/usr/local/faasm/object
        - ./container/shared_store:/usr/local/faasm/shared_store
    working_dir: /usr/local/code/faasm
    privileged: true
    environment:
      - FUNCTION_STORAGE=local
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis

