---

- name: "System deps for protobuf"
  become: yes
  apt:
    name:
    - autoconf
    - automake
    - libtool
    - curl
    - make
    - unzip
    - zlib1g-dev

- name: "Check if protobuf installed"
  stat:
    path: /usr/lib/libprotobuf.so
  register: pb_stat

- name: "Download protobuf source"
  shell: "{{ item }}"
  args:
    chdir: "/tmp/"
  with_items:
    - "curl -O -L https://github.com/google/protobuf/releases/download/v3.12.4/protobuf-cpp-3.12.4.tar.gz"
    - "tar --no-same-owner -xf protobuf-cpp-3.12.4.tar.gz"
  when: pb_stat.stat.exists == False

- name: "Build and install"
  become: yes
  shell: "{{ item }}"
  args:
    chdir: "/tmp/protobuf-3.12.4"
  with_items:
    - "./configure --prefix=/usr CC=/usr/bin/clang-10 CPP=/usr/bin/clang-cpp-10 CXX=/usr/bin/clang++-10"
    - "make -j"
    - "make install"
    - "ldconfig"
  when: pb_stat.stat.exists == False

- name: "Clean up"
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/tmp/protobuf-cpp-3.12.4.tar.gz"
    - "/tmp/protobuf-cpp-3.12.4"
