---

apiVersion: v1
kind: Pod
metadata:
  name: upload
  namespace: faasm
  labels:
    app: faasm
    role: upload
spec:
  containers:
    - name: upload
      image: faasm/upload:0.6.6
      ports:
        - containerPort: 8002
      env:
        - name: REDIS_STATE_HOST
          value: redis-state
        - name: REDIS_QUEUE_HOST
          value: redis-queue
        - name: LOG_LEVEL
          value: "info"
        - name: LD_LIBRARY_PATH
          value: "/build/faasm/third-party/lib:/usr/local/lib"

---

apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: faasm
spec:
  selector:
    role: upload
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002

