---

apiVersion: v1
kind: Pod
metadata:
  name: upload
  namespace: faasm
  labels:
    app: faasm
    role: upload
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: faasm.io/role
            operator: In
            values:
            - control
  containers:
    - name: upload
      image: faasm.azurecr.io/upload:0.27.0
      ports:
        - containerPort: 8002
        - containerPort: 5000
      env:
        - name: REDIS_STATE_HOST
          value: "redis-state"
        - name: REDIS_QUEUE_HOST
          value: "redis-queue"
        - name: PLANNER_HOST
          value: "planner"
        - name: PLANNER_PORT
          value: "8081"
        - name: LOG_LEVEL
          value: "info"
        - name: LD_LIBRARY_PATH
          value: "/build/faasm/third-party/lib:/usr/local/lib"
        - name: PYTHON_CODEGEN
          value: "on"
        - name: FAASM_WASM_VM
          value: "wavm"
