apiVersion: v1
kind: ConfigMap
metadata:
  name: faasm-config
  namespace: faasm
data:
  REDIS_STATE_HOST: redis-state
  REDIS_QUEUE_HOST: redis-queue
  REDIS_PORT: "6379"
  FUNC_ROOT: "/usr/share/faasm"
  LOG_LEVEL: "info"
  PREWARM_TARGET: "120"
  MAX_QUEUE_RATIO: "1"
  MAX_WORKERS_PER_FUNCTION: "20"
  STATE_STALE_THRESHOLD: "3000"
  STATE_CLEAR_THRESHOLD: "30000"
  STATE_PUSH_INTERVALL: "50"
  CGROUP_MODE: "on"
  NETNS_MODE: "on"
