apiVersion: v1
kind: ConfigMap
metadata:
  name: faasm-config
  namespace: faasm
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  FUNC_ROOT: "/usr/share/faasm"
  LOG_LEVEL: "info"
  PREWARM_TARGET: "120"
  MAX_QUEUE_RATIO: "1"
  MAX_WORKERS_PER_FUNCTION: "80"
  CGROUP_MODE: "on"
  NETNS_MODE: "on"
