apiVersion: v1
kind: ConfigMap
metadata:
  name: faasm-config
  namespace: faasm
data:
  REDIS_STATE_HOST: redis-state
  REDIS_QUEUE_HOST: redis-queue
  REDIS_PORT: "6379"
  FUNC_ROOT: "/usr/share/faasm"
  LOG_LEVEL: "info"
  CGROUP_MODE: "on"
  NETNS_MODE: "off"
  THREADS_PER_WORKER: "80"
  PREWARM_TARGET: "0"
  MAX_QUEUE_RATIO: "1"
  MAX_WORKERS_PER_FUNCTION: "20"
  AFFINITY: "1"
  BOUND_TIMEOUT: "10"
  UNBOUND_TIMEOUT: "5000"
  STATE_STALE_THRESHOLD: "60000"
  STATE_CLEAR_THRESHOLD: "300000"
  STATE_PUSH_INTERVALL: "500"
  FULL_ASYNC: "1"
