apiVersion: v1
kind: ConfigMap
metadata:
  name: faasm-config
  namespace: faasm
data:
  REDIS_STATE_HOST: redis-state
  REDIS_QUEUE_HOST: redis-queue
  REDIS_PORT: "6379"
  FUNC_ROOT: "/usr/share/faasm"
  LOG_LEVEL: "debug"
  PREWARM_TARGET: "200"
  MAX_QUEUE_RATIO: "1"
  MAX_WORKERS_PER_FUNCTION: "20"
  STATE_STALE_THRESHOLD: "500"
  STATE_CLEAR_THRESHOLD: "300000"
  STATE_PUSH_INTERVALL: "500"
  FULL_ASYNC: "0"
  AFFINITY: "0"
  CGROUP_MODE: "on"
  NETNS_MODE: "on"
