apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: faasm
spec:
  selector:
    role: edge
  type: LoadBalancer
  externalIPs:
  - 192.168.10.46   # NOTE: this must be changed if the master node is changed
  ports:
  - port: 8001
    targetPort: 8001
