---

- name: "Add LLVM GPG key"
  become: yes
  apt_key: url=https://apt.llvm.org/llvm-snapshot.gpg.key

- name: "Install LLVM 10 repo"
  become: yes
  apt_repository:
    repo: "deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }}-10 main"
    state: present

- name: "Install LLVM"
  become: yes
  apt:
    name:
      - llvm-10
      - llvm-10-dev
      - llvm-10-tools
      - llvm-10-runtime
      - lld-10
      - lldb-10
      - libllvm10
      - libomp-10-dev
      - libc++-10-dev
      - libc++abi-10-dev
    update_cache: yes

- name: "Install Clang"
  become: yes
  apt:
    name:
      - clang-10
      - clangd-10
      - clang-tools-10
      - libclang-10-dev
      - libclang-common-10-dev
      - libclangcpp-10
      - libclangcpp-10-dev
    update_cache: yes

#- name: "Default symlinks"
#  become: yes
#  file:
#    state: link
#    src: "/usr/bin/{{ item }}-10"
#    dest: "/usr/bin/{{ item }}"
#  with_items:
#    - "clang"
#    - "clang++"
#    - "clang-cpp"
#    - "wasm-ld"
#    - "lld"
#    - "llvm-ar"
#    - "llvm-config"
#    - "llvm-nm"
#    - "llvm-ranlib"
