apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: faasm
spec:
  selector:
    role: upload
  type: LoadBalancer
  externalIPs:
    - 192.168.0.38   # Must match the master host
  ports:
    - port: 8002
      targetPort: 8002
