---

- name: "Install deps with apt"
  become: yes
  apt:
    update_cache: yes
    name:
      - cmake
      - software-properties-common
      - libz-dev
      - libboost-dev
      - libcpprest-dev
      - libcairo2-dev
      - libhiredis-dev
      - libcgroup-dev
      - libcurl4-openssl-dev
      - cgroup-tools
      - iproute2
      - iptables
      - valgrind
      - kcachegrind
      - redis-server
      - redis-tools
      - ninja-build
      - python-dev
      - python3-dev
      - python3-pip
      - python3-venv
      - graphviz
    state: present

