apiVersion: v1
kind: ConfigMap
metadata:
  name: faasm-config
  namespace: faasm
data:
  REDIS_STATE_HOST: redis-state
  REDIS_QUEUE_HOST: redis-queue
  REDIS_PORT: "6379"
  FUNCTION_STORAGE: "fileserver"
  FILESERVER_URL: "http://upload:8002"
  LOG_LEVEL: "debug"
  CGROUP_MODE: "off"
  NETNS_MODE: "off"
  THREADS_PER_WORKER: "20"
  MAX_QUEUE_RATIO: "1"
  MAX_WORKERS_PER_FUNCTION: "20"
  GLOBAL_MESSAGE_TIMEOUT: "300000"
  BOUND_TIMEOUT: "300"
  UNBOUND_TIMEOUT: "5000"
  STATE_STALE_THRESHOLD: "60000"
  STATE_CLEAR_THRESHOLD: "300000"
  STATE_PUSH_INTERVALL: "500"
  FULL_ASYNC: "0"
