---

apiVersion: v1
kind: Pod
metadata:
  name: upload
  namespace: faasm
  labels:
    app: faasm
    role: upload
spec:
  containers:
    - name: upload
      image: faasm.azurecr.io/upload:0.9.8
      ports:
        - containerPort: 8002
        - containerPort: 5000
      env:
        - name: REDIS_STATE_HOST
          value: "redis-state"
        - name: REDIS_QUEUE_HOST
          value: "redis-queue"
        - name: LOG_LEVEL
          value: "info"
        - name: LD_LIBRARY_PATH
          value: "/build/faasm/third-party/lib:/usr/local/lib"
        - name: PYTHON_CODEGEN
          value: "off"
        - name: WASM_VM
          value: "sgx"
