---

apiVersion: v1
kind: Pod
metadata:
  name: redis-queue
  namespace: faasm
  labels:
    app: faasm
    role: redis-queue
spec:
  containers:
    - name: master
      image: faasm/redis:0.5.11
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
#  affinity:
#     # Use affinity to make sure this sits on a redis-only box
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: nodeRole
#                operator: In
#                values:
#                  - redis
