---

- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: 'install python'
      raw: 'sudo apt-get -y install python'
  roles:
    - llvm
    - clang
    - protobuf
    - perf
    - linux
    - code
    - python
    - spdlog
    - rapidjson
    - aws_sdk
    - emsdk