---

- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: "Install python"
      raw: "sudo apt-get -y install python"
  roles:
    - linux
    - llvm9
    - protobuf
    - perf
    - code
    - openmpi
    - python
    - spdlog
    - eigen
    - cereal
    - capacity
    - pistache
    - rapidjson
    - docker
    - runtime_fs
