---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Set up dir"
      become: yes
      file: 
        path: "/usr/local/lib/cmake-3.15"
        state: directory

    - name: "Download script"
      become: yes
      shell: "{{ item }}"
      args:
        chdir: /usr/local/lib/cmake-3.15
      with_items:
        - "wget https://github.com/Kitware/CMake/releases/download/v3.15.0/cmake-3.15.0-Linux-x86_64.sh"
        - "chmod +x cmake-3.15.0-Linux-x86_64.sh"
    
    - name: "Execute script"
      become: yes
      shell: "./cmake-3.15.0-Linux-x86_64.sh --skip-license"
      args:
        chdir: /usr/local/lib/cmake-3.15
