---

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: "System deps"
      become: yes
      apt:
        name:
          - nasm

    # 27/08/20 - currently only Ubuntu 18.04 available
    - name: "Download SGX installers"
      get_url:
        url: "https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server/{{ item }}"
        dest: "/tmp/{{ item }}"
        mode: "0755"
      with_items:
        - "sgx_linux_x64_driver_2.6.0_602374c.bin"
        - "sgx_linux_x64_sdk_2.10.100.2.bin"
