---

- name: "Add LLVM GPG key"
  become: yes
  apt_key: url=https://apt.llvm.org/llvm-snapshot.gpg.key

- name: "Add LLVM 9 repo"
  become: yes
  apt_repository:
    repo: "deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }}-9 main"
    state: present

- name: "Install llvm and other deps"
  become: yes
  apt:
    name:
      - llvm-9
      - llvm-9-dev
      - llvm-9-tools
      - lld-9
      - lldb-9
    update_cache: yes

- name: "Install clang and other deps"
  become: yes
  apt:
    name:
      - clang-9
      - clang-tools-9
      - libclang-9-dev
    update_cache: yes

- name: "Symlinks"
  become: yes
  file:
    state: link
    src: "/usr/bin/{{ item }}-9"
    dest: "/usr/bin/{{ item }}"
  with_items:
    - "clang"
    - "clang++"
    - "clang-cpp"
    - "lld"
    - "lldb"
    - "llvm-ar"
    - "llvm-config"
    - "llvm-nm"
    - "llvm-ranlib"
    - "wasm-ld"
